import google.generativeai as genai
import os

GEMINI_API_KEY = "YOUR_GEMINI_API_KEY_HERE"

def initialize_gemini():
    if GEMINI_API_KEY == "YOUR_GEMINI_API_KEY_HERE":
        return None
    genai.configure(api_key=GEMINI_API_KEY)
    return genai.GenerativeModel('gemini-pro')

def generate_explanation(values, risk_level):
    try:
        model = initialize_gemini()
        
        if model is None:
            return get_default_explanation(values, risk_level)
        
        prompt = f"""You are a medical assistant. A machine learning model has predicted a {risk_level} health risk based on the following medical values:

- Hemoglobin: {values['hemoglobin']} g/dL (Normal: 13.5-17.5 for men, 12-15.5 for women)
- Blood Sugar: {values['blood_sugar']} mg/dL (Normal: 70-110 fasting)
- Cholesterol: {values['cholesterol']} mg/dL (Normal: <200)

Predicted Risk Level: {risk_level}

Please provide:
1. A simple explanation of what these values mean
2. Which specific values contributed to this risk level
3. General health recommendations

IMPORTANT: Include a disclaimer that this is not a medical diagnosis and the user should consult a healthcare professional.

Keep the explanation clear, concise, and easy to understand for a general audience."""

        response = model.generate_content(prompt)
        return response.text
        
    except Exception as e:
        print(f"Gemini API Error: {str(e)}")
        return get_default_explanation(values, risk_level)

def get_default_explanation(values, risk_level):
    explanation = f"<strong>Health Risk Assessment: {risk_level}</strong><br><br>"
    
    explanation += "<strong>Your Values:</strong><br>"
    explanation += f"• Hemoglobin: {values['hemoglobin'] if values['hemoglobin'] is not None else 'Not detected'} {'g/dL' if values['hemoglobin'] is not None else ''}<br>"
    explanation += f"• Blood Sugar: {values['blood_sugar'] if values['blood_sugar'] is not None else 'Not detected'} {'mg/dL' if values['blood_sugar'] is not None else ''}<br>"
    explanation += f"• Cholesterol: {values['cholesterol'] if values['cholesterol'] is not None else 'Not detected'} {'mg/dL' if values['cholesterol'] is not None else ''}<br><br>"
    
    explanation += "<strong>Analysis:</strong><br>"
    
    if values['hemoglobin'] is not None:
        if values['hemoglobin'] < 12:
            explanation += "• Your hemoglobin level is low, which may indicate anemia.<br>"
        elif values['hemoglobin'] > 17.5:
            explanation += "• Your hemoglobin level is elevated.<br>"
        else:
            explanation += "• Your hemoglobin level is within normal range.<br>"
    else:
        explanation += "• Hemoglobin value not found in the report.<br>"
    
    if values['blood_sugar'] is not None:
        if values['blood_sugar'] > 140:
            explanation += "• Your blood sugar is high, indicating possible diabetes risk.<br>"
        elif values['blood_sugar'] > 110:
            explanation += "• Your blood sugar is slightly elevated (pre-diabetic range).<br>"
        else:
            explanation += "• Your blood sugar level is normal.<br>"
    else:
        explanation += "• Blood sugar value not found in the report.<br>"
    
    if values['cholesterol'] is not None:
        if values['cholesterol'] > 240:
            explanation += "• Your cholesterol is high, increasing cardiovascular risk.<br>"
        elif values['cholesterol'] > 200:
            explanation += "• Your cholesterol is borderline high.<br>"
        else:
            explanation += "• Your cholesterol level is normal.<br>"
    else:
        explanation += "• Cholesterol value not found in the report.<br>"
    
    explanation += "<br><strong>Recommendations:</strong><br>"
    
    if risk_level == 'High':
        explanation += "• Consult a healthcare professional immediately<br>"
        explanation += "• Consider lifestyle modifications<br>"
        explanation += "• Schedule regular health check-ups<br>"
    elif risk_level == 'Medium':
        explanation += "• Schedule a check-up with your doctor<br>"
        explanation += "• Monitor your health parameters regularly<br>"
        explanation += "• Maintain a healthy diet and exercise routine<br>"
    else:
        explanation += "• Continue maintaining a healthy lifestyle<br>"
        explanation += "• Regular health check-ups are still recommended<br>"
    
    explanation += "<br><strong>⚠️ MEDICAL DISCLAIMER:</strong><br>"
    explanation += "This analysis is generated by a machine learning model and is not a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider for medical concerns."
    
    return explanation

def get_health_tips(values, risk_level):
    """
    Generate personalized health tips based on medical values
    """
    tips = []
    
    # Hemoglobin tips (only if value exists)
    if values['hemoglobin'] is not None:
        if values['hemoglobin'] < 12:
            tips.append("🥬 Eat iron-rich foods: spinach, red meat, beans, lentils, and fortified cereals")
            tips.append("🍊 Consume vitamin C to improve iron absorption (citrus fruits, tomatoes)")
            tips.append("☕ Avoid tea/coffee with meals as they reduce iron absorption")
        elif values['hemoglobin'] > 17.5:
            tips.append("💧 Stay well hydrated - drink at least 8 glasses of water daily")
            tips.append("🚭 Avoid smoking as it can elevate hemoglobin levels")
    
    # Blood sugar tips (only if value exists)
    if values['blood_sugar'] is not None:
        if values['blood_sugar'] > 140:
            tips.append("🚶 Exercise for at least 30 minutes daily - walking, jogging, or cycling")
            tips.append("🍎 Reduce sugar and refined carbs intake (white bread, pastries, soda)")
            tips.append("💧 Drink plenty of water throughout the day")
            tips.append("⏰ Eat smaller, frequent meals instead of large meals")
        elif values['blood_sugar'] > 110:
            tips.append("🏃 Increase physical activity - aim for 150 minutes per week")
            tips.append("🥗 Choose whole grains over refined carbohydrates")
            tips.append("⚖️ Maintain a healthy weight")
    
    # Cholesterol tips (only if value exists)
    if values['cholesterol'] is not None:
        if values['cholesterol'] > 240:
            tips.append("🥗 Eat more fiber: oats, beans, vegetables, and fruits")
            tips.append("🐟 Include omega-3 fatty acids: fatty fish (salmon, mackerel), walnuts, flaxseeds")
            tips.append("🚫 Limit saturated fats (red meat, butter) and avoid trans fats")
            tips.append("🥑 Use healthy fats like olive oil and avocados")
        elif values['cholesterol'] > 200:
            tips.append("🍽️ Reduce dietary cholesterol from animal products")
            tips.append("🏋️ Regular exercise can help lower cholesterol")
            tips.append("🌰 Add nuts and seeds to your diet (in moderation)")
    
    # General wellness tips for low risk
    if risk_level == 'Low' and len(tips) == 0:
        tips.append("✅ Excellent! Keep up the good work maintaining your health")
        tips.append("🏃 Continue regular exercise (at least 150 minutes per week)")
        tips.append("🥗 Maintain a balanced diet with fruits, vegetables, and whole grains")
        tips.append("😴 Get 7-8 hours of quality sleep each night")
        tips.append("🧘 Practice stress management techniques")
    
    # Add general tips based on risk level
    if risk_level == 'High':
        tips.append("⚠️ IMPORTANT: Consult a healthcare professional immediately")
        tips.append("📋 Schedule regular health check-ups and monitoring")
    elif risk_level == 'Medium':
        tips.append("👨‍⚕️ Schedule a check-up with your doctor soon")
        tips.append("📊 Monitor your health parameters regularly")
    
    return tips
